### ISSUE TITLE
フォントカラーの対応

### ISSUE THREAD

**Issue by ktanaka117** [EZ-NET/CodePiece#10]
xcodeのフォントのDefaultだとフォントカラー的に問題ないのですが、Midnightなど他のテーマを使っていると白地のフォントカラーが無効になってしまうので、CodePieceにカラーテーマを増やして欲しい

白地のフォントを使っているとCodePieceの背景色が白のため字が見えなくなってしまう
![2016-06-11 11 01 09](https://cloud.githubusercontent.com/assets/4278711/15982512/e32c6a72-2fc4-11e6-88c2-ca9e88104b0b.png)
![2016-06-11 11 02 16](https://cloud.githubusercontent.com/assets/4278711/15982513/e77af9b8-2fc4-11e6-9b69-582a04191cd5.png)

**Comment by takasek** [comment]
別の対策としては、CodeTextViewのrichTextをfalseにするというのもありかなあと思います。

**Comment by es-kumagai** [comment]
田中さん！ ご報告、ありがとうございます！
そしてひとまず、高瀬さんに教えて頂いた方法をとらせて頂きます！

ありがとうございます！
