### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by masakih** [EZ-NET/CodePiece#11]
1. setting up both accounts and clear hash tag.
2. restart CodePiece
3. brown item it has upper arrow, apear in twitter time line upside.
4. click that item.
5. 'Open In Twitter' button is turn to enable. (This is bug.)
6. click 'Open In Twitter' button to crash.

piece of Crach report.

> Process:               CodePiece [75099]
> Path:                  /Applications/CodePiece.app/Contents/MacOS/CodePiece
> Identifier:            jp.ez-style.appid.CodePiece
> Version:               1.4.12 (62)
> App Item ID:           1021284423
> App External ID:       818426232
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           CodePiece [75099]
> User ID:               502
> 
> Date/Time:             2017-03-22 23:54:20.530 +0900
> OS Version:            Mac OS X 10.12.3 (16D32)
> Report Version:        12
> Anonymous UUID:        60329EEA-C6A3-0CB4-1736-9DBE4395A3EC

----
> Application Specific Information:
> Performing @selector(openBrowserWithCurrentTwitterStatus:) from sender NSButton 0x600000147fe0
> fatal error: Cannot open browser.: file /Data/Development/Projects/CodePiece/CodePiece/ViewController.swift, line 383

英語がよくわからないので日本語で

1. 両アカウントを設定し、ハッシュタグをクリアします
2. CodePiece　を再起動します
3. タイムラインの上部に上矢印がついた茶色のアイテムが出現します
4. 茶色のアイテムをクリックします
5. 'Open In Twitter'ボタンが有効になります (これが大元のバグです)
6. 'Open In Twitter' をクリックするとクラッシュします

**Comment by es-kumagai** [comment]
ありがとうございます！
